.openpublishing.publish.config.json, dsc/docfx.json
* Update config for feedback & public contributions
=> Update config for feedback & public contributions (#23)

dsc/docs-conceptual/dsc-1.1/getting-started/winGettingStarted.md, dsc/docs-conceptual/dsc-1.1/resources/authoringResourceClass.md, dsc/docs-conceptual/dsc-2.0/overview.md
Publishing latest changes to live
=> Publish to live

dsc/breadcrumb/toc.yml
Fixes AB#1916242 - Update breadcrumb toc
=> Update breadcrumb toc

dsc/docs-conceptual/dsc-1.1/pull-server/pullServer.md, dsc/docs-conceptual/dsc-1.1/pull-server/secureServer.md, dsc/docs-conceptual/dsc-3.0/getting-started/getting-started.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Get-DscResource.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Remove-DscConfigurationDocument.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Set-DscLocalConfigurationManager.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Start-DscConfiguration.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Stop-DscConfiguration.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Test-DscConfiguration.md, dsc/dsc-2.0/PSDesiredStateConfiguration/Get-DscResource.md, dsc/dsc-3.0/PSDesiredStateConfiguration/Get-DscResource.md
Fixes AB#1932258 - Fix broken links from report
=> Fix broken links from report

.github/ISSUE_TEMPLATE/New_Document.yml, .github/ISSUE_TEMPLATE/New_Feature.yml, .github/ISSUE_TEMPLATE/New_Issue.yml, .github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE.md, .github/SUPPORT.md
Fixes AB#1933826 - Add issue and PR templates
=> Add issue and PR templates

dsc/dsc-1.1/PSDesiredStateConfiguration/Disable-DscDebug.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Enable-DscDebug.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Get-DscConfiguration.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Get-DscConfigurationStatus.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Get-DscLocalConfigurationManager.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Get-DscResource.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Invoke-DscResource.md, dsc/dsc-1.1/PSDesiredStateConfiguration/New-DSCCheckSum.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Publish-DscConfiguration.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Remove-DscConfigurationDocument.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Restore-DscConfiguration.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Set-DscLocalConfigurationManager.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Start-DscConfiguration.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Stop-DscConfiguration.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Test-DscConfiguration.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Update-DscConfiguration.md
Fix H2 letter case for localization
=> Fix H2 letter case for localization

dsc/docs-conceptual/dsc-1.1/getting-started/winGettingStarted.md
Fixes a typo in the getting started documentation for Windows in v1.1, removing passive voice at the same time.
- Fixes #55 
Check the boxes below to indicate the content affected by this PR.
**Repository or docset configuration**
**Conceptual documentation**
**Cmdlet reference & about_ topics**
When changing **cmdlet reference** or **about_ topics**, the changes should be copied to all
relevant versions. Check the boxes below to indicate the versions affected by this change.
please add the prefix `WIP:` or `[WIP]` to the beginning of the title and remove the prefix when
the PR is ready.
[key]: https://help.github.com/en/articles/closing-issues-using-keywords
=> (GH-55) Rewrite typo sentence for clarity

.github/messages/expectations.md, .github/workflows/checklist.yml, .github/workflows/expectations.yml, .github/workflows/targeting-repo-files.yml, .github/workflows/targeting-valid-branch.yml
Prior to this change, the repository was configured to use one workflow to verify if a user submitting a Pull Request to the `live` branch was authorized to do so.
This change updates the existing workflow to use the new actions added to MicrosoftDocs/PowerShell-Docs in MicrosoftDocs/PowerShell-Docs#8917.
It also adds three new workflows:
- `checklist.yml` triggers on Pull Requests when the Pull Request is not in draft and does not have a `WIP` prefix; it inspects the body of the Pull Request to find mandatory checklist items and reports whether or not they have been filled out; if they have not been, it fails and reports that the checklist is missing mandatory items.
- `expectations.yml` triggers on a schedule to search for open Pull Requests to the `main` branch which do not already …
=> (MAINT) Use new actions for workflows

.github/CODEOWNERS
Adds the CODEOWNERS file to the repo for automatic review tagging.
=> (MAINT) Add code owners

dsc/dsc-1.1/PSDesiredStateConfiguration/Start-DscConfiguration.md
=> Grammar fix

.github/workflows/expectations.yml
=> (MAINT) Set expectations workflow to 10m

dsc/docs-conceptual/dsc-2.0/configurations/configDataCredentials.md, dsc/docs-conceptual/dsc-2.0/configurations/configurations.md, dsc/docs-conceptual/dsc-2.0/configurations/runAsUser.md, dsc/docs-conceptual/dsc-2.0/resources/authoringResourceClass.md, dsc/docs-conceptual/dsc-2.0/resources/get-test-set.md, dsc/docs-conceptual/dsc-2.0/resources/resourceAuthoringChecklist.md, dsc/docs-conceptual/dsc-2.0/troubleshooting/troubleshooting.md
Prior to this change, documentation for v2 referenced the Pull Server, which is removed in v2.
This change:
- Removes direct references to the Pull Server
- Resolves [AB#4242](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4242)
=> (AB#4242) Remove references to Pull Server for v2

dsc/breadcrumb/toc.yml
**Global effort to fix broken links**
The C+E Skilling team is fixing broken links on docs.microsoft.com. This effort will eliminate potential accessibility, security, and usability issues. This PR updates the breadcrumb TOC, which should address ~150 link errors. Thanks!
=> [BrokenLinks] update breadcrumbs file

dsc/breadcrumb/toc.yml, dsc/docfx.json, dsc/docs-conceptual/dsc-3.0/toc.yml
I've added the PSDesiredStateConfiguration module path to the breadcrumb file, and I specified both paths (conceptual and module) in the breadcrumb_path configuration. Fingers crossed that this is the missing piece!
=> [BrokenLinks] fix breadcrumbs, part 3

dsc/docs-conceptual/dsc-2.0/configurations/add-parameters-to-a-configuration.md, dsc/docs-conceptual/dsc-2.0/configurations/compositeConfigs.md, dsc/docs-conceptual/dsc-2.0/configurations/configData.md, dsc/docs-conceptual/dsc-2.0/configurations/configDataCredentials.md, dsc/docs-conceptual/dsc-2.0/configurations/configHelp.md, dsc/docs-conceptual/dsc-2.0/configurations/configurations.md, dsc/docs-conceptual/dsc-2.0/configurations/flow-control-in-configurations.md, dsc/docs-conceptual/dsc-2.0/configurations/import-dscresource.md, dsc/docs-conceptual/dsc-2.0/configurations/install-additional-dsc-resources.md, dsc/docs-conceptual/dsc-2.0/configurations/resource-depends-on.md, dsc/docs-conceptual/dsc-2.0/configurations/separatingEnvData.md, dsc/docs-conceptual/dsc-2.0/configurations/sxsResource.md, dsc/docs-conceptual/dsc-2.0/configurations/write-compile-configuration.md, dsc/docs-conceptual/dsc-2.0/getting-started/invoking-dsc-resources.md, dsc/docs-conceptual/dsc-2.0/overview.md, dsc/docs-conceptual/dsc-2.0/resources/authoringResource.md, dsc/docs-conceptual/dsc-2.0/resources/authoringResourceClass.md, dsc/docs-conceptual/dsc-2.0/resources/authoringResourceComposite.md, dsc/docs-conceptual/dsc-2.0/resources/authoringResourceMOF.md, dsc/docs-conceptual/dsc-2.0/resources/get-test-set.md, dsc/docs-conceptual/dsc-2.0/resources/resourceAuthoringChecklist.md, dsc/docs-conceptual/dsc-2.0/resources/resources.md, dsc/docs-conceptual/dsc-2.0/resources/singleInstance.md, dsc/docs-conceptual/dsc-2.0/troubleshooting/debugResource.md, dsc/docs-conceptual/dsc-2.0/troubleshooting/troubleshooting.md
This PR makes broad changes to the documents in the v2 docset and:
- Updates the `description` metadata to always use the YAML `>` syntax to enable longer lines
- Updates the style of all included code blocks to match the docs style
- Replaces all inline links with numbered reference links
- Begins to standardize terminology and markup for DSC. This will be fully addressed in a future change which defines terminology in a referable page.
- Fixes [AB#4589](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4589)
=> (AB#4589) Improve DSC v2 maintainability

dsc/docs-conceptual/dsc-2.0/terminology.md, dsc/docs-conceptual/dsc-2.0/toc.yml
Prior to this change, the terminology for DSC used a mix of casing and
was not always clear because the terms `Configuration`, `Resource`, and
`Node`, in particular, are overloaded.
This change adds a new document to list and briefly explain terms used
for DSC. This document should form the basis of how these concepts are
written in the documentation and all formatting and usage should be
updated to comply with the standards set here.
=> (AB-4757) Add terminology for DSC

dsc/docs-conceptual/dsc-1.1/resources/authoringResourceClass.md
=> Fixed typo on authoringResourceClass.md

dsc/docs-conceptual/dsc-1.1/toc.yml
This change adds an entry to the v1.1 TOC to link readers to the **PSDscResources** documentation in the v2 docs.
- Fixes [AB#4581](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4581)
=> (AB-4581) Add PSDscResource link to v1.1

.github/PULL_REQUEST_TEMPLATE.md, .github/messages/expectations.md, dsc/dsc-1.1/PSDesiredStateConfiguration/About/about_Classes_and_DSC.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Disable-DscDebug.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Enable-DscDebug.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Get-DscConfiguration.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Get-DscConfigurationStatus.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Get-DscLocalConfigurationManager.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Get-DscResource.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Invoke-DscResource.md, dsc/dsc-1.1/PSDesiredStateConfiguration/New-DSCCheckSum.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Publish-DscConfiguration.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Remove-DscConfigurationDocument.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Restore-DscConfiguration.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Set-DscLocalConfigurationManager.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Start-DscConfiguration.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Stop-DscConfiguration.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Test-DscConfiguration.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Update-DscConfiguration.md, dsc/dsc-2.0/PSDesiredStateConfiguration/About/about_Classes_and_DSC.md, dsc/dsc-2.0/PSDesiredStateConfiguration/Get-DscResource.md, dsc/dsc-2.0/PSDesiredStateConfiguration/Invoke-DscResource.md, dsc/dsc-2.0/PSDesiredStateConfiguration/New-DSCCheckSum.md, dsc/dsc-3.0/PSDesiredStateConfiguration/ConvertTo-DscJsonSchema.md, dsc/dsc-3.0/PSDesiredStateConfiguration/Get-DscResource.md, dsc/dsc-3.0/PSDesiredStateConfiguration/Invoke-DscResource.md, dsc/dsc-3.0/PSDesiredStateConfiguration/New-DscChecksum.md
Fixes [AB#6853](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/6853) - Update URLs for site rebrand
=> Update URLs for site rebrand

dsc/docfx.json
Related to [AB#26794](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/26794) - Update metadata in docfx
=> Update metadata in docfx

dsc/docfx.json
Add index.md to file list in docfx
=> Add index.md to file list in docfx

.github/ISSUE_TEMPLATE/00-bug.yml, .github/ISSUE_TEMPLATE/01-article.yml, .github/ISSUE_TEMPLATE/02-quality.yml, .github/ISSUE_TEMPLATE/03-change.yml, .github/workflows/quality.issue.yml, .github/workflows/quality.pr.yml
This change updates the github actions and templates to align with the label changes and use of project automation.
- Fixes [AB#62327](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/62327)
=> (AB-62327) Update GHA/templates

dsc/docs-conceptual/dsc-1.1/getting-started/lnxGettingStarted.md
Added a note on support for DSC Linux.
=> Added a note on support for DSC Linux 

dsc/docs-conceptual/dsc-2.0/getting-started/invoking-dsc-resources.md
Prior to this change the example for the **Get** method in the Invoking DSC Resource article did not work. This change fixes the example.
=> (MAINT) Fix example in Invoke-DscResource

dsc/docs-conceptual/dsc-2.0/getting-started/invoking-dsc-resources.md
Prior to this change the example for the **Get** method in the Invoking DSC Resource article did not work. This change fixes the example.
=> (MAINT) Fix example in Invoke-DscResource (#136)

dsc/breadcrumb/toc.yml
=> Flatten breadcrumbs

dsc/includes/dsc-resources.md
Fixes a missing word and updates the link to the docs instead of the repository readme.
=> (MAINT) Fixes missing word in include for PSDscResources

dsc/docs-conceptual/dsc-1.1/configurations/install-additional-dsc-resources.md, dsc/docs-conceptual/dsc-2.0/how-tos/installing-dsc-resources.md
This change fixes broken links to the moved Gallery content.
=> (MAINT) Fix broken links

.openpublishing.publish.config.json, dsc/docfx.json
Update and sort json config files
=> Update and sort json config files

dsc/docs-conceptual/dsc-2.0/overview.md
Updates the referenced version for v2 to the latest release.
- Related to [AB#90281](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/90281)
=> (AB-90281) Update DSC v2 to v2.0.7

dsc/docs-conceptual/dsc-2.0/overview.md
Updates the referenced version for v2 to the latest release.
- Related to [AB#90281](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/90281)
=> 5/15/2023 PM Publish

dsc/docs-conceptual/dsc-1.1/pull-server/pullClient.md, dsc/docs-conceptual/dsc-1.1/pull-server/pullClientConfigID.md, dsc/docs-conceptual/dsc-1.1/pull-server/pullClientConfigID4.md, dsc/docs-conceptual/dsc-1.1/pull-server/pullClientConfigNames.md, dsc/docs-conceptual/dsc-1.1/pull-server/pullServer.md, dsc/docs-conceptual/dsc-1.1/pull-server/pullServerSMB.md, dsc/docs-conceptual/dsc-1.1/pull-server/reportServer.md, dsc/docs-conceptual/dsc-1.1/pull-server/secureServer.md
Recommend GC rather than AADSC
=> Update Windows Pull Server docs

dsc/docs-conceptual/dsc-1.1/pull-server/pullClient.md, dsc/docs-conceptual/dsc-1.1/pull-server/pullClientConfigID.md, dsc/docs-conceptual/dsc-1.1/pull-server/pullClientConfigID4.md, dsc/docs-conceptual/dsc-1.1/pull-server/pullClientConfigNames.md, dsc/docs-conceptual/dsc-1.1/pull-server/pullServer.md, dsc/docs-conceptual/dsc-1.1/pull-server/pullServerSMB.md, dsc/docs-conceptual/dsc-1.1/pull-server/reportServer.md, dsc/docs-conceptual/dsc-1.1/pull-server/secureServer.md
* Update Windows Pull Server docs
Recommend GC rather than AADSC
* update remaining pages
* Fix broken links and formatting
* fix build warning
---------
=> 6/21/2023 PM Publish

dsc/docs-conceptual/dsc-3.0/concepts/configurations.md, dsc/docs-conceptual/dsc-3.0/overview.md
=> 6/28/2023 PM Publish

dsc/docs-conceptual/dsc-3.0/overview.md
The v3 preview of the **PSDesiredStateConfiguration** module was unlisted from the PowerShell Gallery. This change:
- updates the installation code snippet to work with the unlisted module
- fixes #168
=> (GH-168) Fix v3 install code

dsc/docs-conceptual/dsc-3.0/overview.md
The v3 preview of the **PSDesiredStateConfiguration** module was unlisted from the PowerShell Gallery. This change:
- updates the installation code snippet to work with the unlisted module
- fixes #168
=> 7/25/2023 PM Publish

.vscode/cspell/dsc/dictionaries/dsc-terms.txt, .vscode/styles/Vocab/PowerShell-Docs/accept.txt, dsc/docs-conceptual/dsc-3.0/concepts/resources.md, dsc/docs-conceptual/dsc-3.0/glossary.md, dsc/docs-conceptual/dsc-3.0/overview.md
This change further clarifies the distinction and terminology to reduce confusion about PowerShell Desired State Configuration in DSCv3.
=> (GH-156) Clarifiy glossary for DSCv3/PSDSC

dsc/docfx.json
=> third try docfx

dsc/docfx.json
Reverts MicrosoftDocs/PowerShell-Docs-DSC#187
=> Revert "third try docfx"

dsc/docs-conceptual/dsc-1.1/reference/resources/windows/registryResource.md
=> 9/18/2023 PM Publish

.github/ISSUE_TEMPLATE/04-customer-feedback.yml, dsc/docfx.json
=> Configure OSS Feedback

dsc/docfx.json
Define OSS Feedback in globalMetadata
=> Define OSS Feedback in globalMetadata

.github/ISSUE_TEMPLATE/04-customer-feedback.yml, dsc/docfx.json
Configure OSS feedback repo name
=> Configure OSS feedback repo name

dsc/docfx.json
Optimize globbing in docfx.json
=> Optimize globbing in docfx.json

.github/ISSUE_TEMPLATE/04-customer-feedback.yml, dsc/docfx.json
=> 9/28/2023 PM Publish

.github/ISSUE_TEMPLATE/04-customer-feedback.yml, dsc/docfx.json
Update feedback config to reduce empty submissions
=> Update feedback config to reduce empty submissions

.github/ISSUE_TEMPLATE/04-customer-feedback.yml, dsc/docfx.json
=> 09/29 PM Publishing 

dsc/docs-conceptual/dsc-3.0/changelog.md, dsc/docs-conceptual/dsc-3.0/reference/cli/resource/set.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/manifest/get.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/manifest/root.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/manifest/set.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/manifest/test.md
This change pulls over the reference documentation updates for the `alpha.3` release of DSCv3.
- Fixes [AB#167446](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/167446)
=> (AB-167446) Sync docs for `alpha.3`

dsc/docs-conceptual/dsc-3.0/changelog.md, dsc/docs-conceptual/dsc-3.0/reference/cli/resource/set.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/manifest/get.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/manifest/root.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/manifest/set.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/manifest/test.md
This change pulls over the reference documentation updates for the `alpha.3` release of DSCv3.
- Fixes [AB#167446](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/167446)
=> 10/05 PM Publishing

dsc/docfx.json
Add config items for the standard feedback control
- Fixes [AB#169517](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/169517)
=> Add config items for the standard feedback control

dsc/docfx.json
=> 10/13/2023 PM Publish

dsc/docfx.json
=> Update UUF glob patterns

dsc/docfx.json
* Update UUF glob patterns
* more globs
* more globs
=> 10/16/2023 PM Publish

dsc/docfx.json
Update product name for UUF configuration
- Fixes [AB#186522](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/186522)
=> Update product name for UUF configuration

dsc/docfx.json
=> 11/28/2023 PM Publish

dsc/docs-conceptual/dsc-1.1/resources/authoringResourceMOF.md, dsc/docs-conceptual/dsc-2.0/how-tos/resources/authoring/mof-based.md
Prior to this change, the how-to articles for creating MOF-based DSC Resources did not include the root module manifest in the list of required files.
This change:
- Adds the root module manifest as a required file in the file list.
- Resolves #215
=> (GH-215) Add root module manifest to MOF file list

dsc/docs-conceptual/dsc-1.1/resources/authoringResourceMOF.md, dsc/docs-conceptual/dsc-2.0/how-tos/resources/authoring/mof-based.md
Prior to this change, the how-to articles for creating MOF-based DSC Resources did not include the root module manifest in the list of required files.
This change:
- Adds the root module manifest as a required file in the file list.
- Resolves #215
=> 11/29/2023 PM Publish

dsc/docs-conceptual/dsc-1.1/reference/resources/windows/scriptResource.md, dsc/docs-conceptual/dsc-2.0/reference/PSDscResources/Resources/Script/Script.md
=> 12/4/2023 PM Publish

.openpublishing.redirection.json
=> Fix redirect status

dsc/docs-conceptual/dsc-1.1/reference/resources/packagemanagement/PackageManagementDscResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/packagemanagement/PackageManagementSourceDscResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/windows/fileResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/windows/packageResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/windows/registryResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/windows/serviceResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/windows/serviceSetResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/windows/windowsFeatureSetResource.md
Add missing `Import-DSCResource` statements to all configuration blocks in examples.
- Resolves #233
- Fixes [AB#196403](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/196403)
=> 1/2/2024 PM Publish

dsc/docfx.json
=> Update globs for ms.topic

dsc/docfx.json
Update metadata for new validation rules
=> Update metadata for new validation rules

dsc/docfx.json
=> 1/10/2024 PM Publish

dsc/docs-conceptual/dsc-3.0/overview.md
Prior to this change, the overview for the DSCv3 documentation included a sentence about installing PowerShell DSC v3, but did not include the code block to actually install the module.
This change:
- Adds the missing code block
- Clarifies that the module is in beta
- Resolves #244
- Fixes [AB#204909](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/204909)
=> (GH-244) Add missing code for PSDSCv3 install

dsc/docs-conceptual/dsc-3.0/overview.md
Prior to this change, the overview for the DSCv3 documentation included a sentence about installing PowerShell DSC v3, but did not include the code block to actually install the module.
This change:
- Adds the missing code block
- Clarifies that the module is in beta
- Resolves #244
- Fixes [AB#204909](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/204909)
=> 1/29/2024 PM Publish

dsc/docs-conceptual/dsc-3.0/changelog.md, dsc/docs-conceptual/dsc-3.0/reference/cli/config/command.md, dsc/docs-conceptual/dsc-3.0/reference/cli/config/export.md, dsc/docs-conceptual/dsc-3.0/reference/cli/config/get.md, dsc/docs-conceptual/dsc-3.0/reference/cli/config/set.md, dsc/docs-conceptual/dsc-3.0/reference/cli/config/test.md, dsc/docs-conceptual/dsc-3.0/reference/cli/dsc.md, dsc/docs-conceptual/dsc-3.0/reference/cli/resource/export.md, dsc/docs-conceptual/dsc-3.0/reference/cli/resource/get.md, dsc/docs-conceptual/dsc-3.0/reference/cli/resource/list.md, dsc/docs-conceptual/dsc-3.0/reference/cli/resource/schema.md, dsc/docs-conceptual/dsc-3.0/reference/cli/resource/set.md, dsc/docs-conceptual/dsc-3.0/reference/cli/resource/test.md, dsc/docs-conceptual/dsc-3.0/reference/cli/schema/command.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/config/functions/concat.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/config/functions/envvar.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/config/functions/parameters.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/outputs/config/set.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/outputs/config/test.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/outputs/resource/get.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/outputs/resource/set.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/outputs/resource/test.md
Updates the reference docs and changelog for the `alpha.5` release of DSC.
=> (MAINT) Sync `alpha.5` docs updates

dsc/docs-conceptual/dsc-3.0/changelog.md, dsc/docs-conceptual/dsc-3.0/reference/cli/config/command.md, dsc/docs-conceptual/dsc-3.0/reference/cli/config/export.md, dsc/docs-conceptual/dsc-3.0/reference/cli/config/get.md, dsc/docs-conceptual/dsc-3.0/reference/cli/config/set.md, dsc/docs-conceptual/dsc-3.0/reference/cli/config/test.md, dsc/docs-conceptual/dsc-3.0/reference/cli/dsc.md, dsc/docs-conceptual/dsc-3.0/reference/cli/resource/export.md, dsc/docs-conceptual/dsc-3.0/reference/cli/resource/get.md, dsc/docs-conceptual/dsc-3.0/reference/cli/resource/list.md, dsc/docs-conceptual/dsc-3.0/reference/cli/resource/schema.md, dsc/docs-conceptual/dsc-3.0/reference/cli/resource/set.md, dsc/docs-conceptual/dsc-3.0/reference/cli/resource/test.md, dsc/docs-conceptual/dsc-3.0/reference/cli/schema/command.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/config/functions/concat.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/config/functions/envvar.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/config/functions/parameters.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/outputs/config/set.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/outputs/config/test.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/outputs/resource/get.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/outputs/resource/set.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/outputs/resource/test.md
Out of band publish for `alpha.5` DSC release.
=> Merge main to live

dsc/docs-conceptual/dsc-1.1/configurations/add-parameters-to-a-configuration.md, dsc/docs-conceptual/dsc-1.1/configurations/crossNodeDependencies.md, dsc/docs-conceptual/dsc-1.1/configurations/reboot-a-node.md, dsc/docs-conceptual/dsc-1.1/configurations/separatingEnvData.md, dsc/docs-conceptual/dsc-1.1/getting-started/lnxGettingStarted.md, dsc/docs-conceptual/dsc-1.1/overview/DscForEngineers.md, dsc/docs-conceptual/dsc-1.1/reference/resources/linux/lnxArchiveResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/linux/lnxEnvironmentResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/linux/lnxFileLineResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/linux/lnxFileResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/linux/lnxGroupResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/linux/lnxPackageResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/linux/lnxScriptResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/linux/lnxServiceResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/linux/lnxSshAuthorizedKeysResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/linux/lnxUserResource.md, dsc/docs-conceptual/dsc-1.1/resources/authoringResourceClass.md, dsc/docs-conceptual/dsc-1.1/resources/authoringResourceComposite.md, dsc/docs-conceptual/dsc-2.0/how-tos/resources/authoring/class-based.md, dsc/docs-conceptual/dsc-2.0/how-tos/resources/authoring/composite.md, dsc/dsc-1.1/PSDesiredStateConfiguration/About/about_Classes_and_DSC.md, dsc/dsc-2.0/PSDesiredStateConfiguration/About/about_Classes_and_DSC.md
Fix parameter name
- Fixes [AB#227658](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/227658)
- Fixes #251
=> Fixes #251 - Fix parameter name

dsc/docs-conceptual/dsc-1.1/configurations/add-parameters-to-a-configuration.md, dsc/docs-conceptual/dsc-1.1/configurations/crossNodeDependencies.md, dsc/docs-conceptual/dsc-1.1/configurations/reboot-a-node.md, dsc/docs-conceptual/dsc-1.1/configurations/separatingEnvData.md, dsc/docs-conceptual/dsc-1.1/getting-started/lnxGettingStarted.md, dsc/docs-conceptual/dsc-1.1/overview/DscForEngineers.md, dsc/docs-conceptual/dsc-1.1/reference/resources/linux/lnxArchiveResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/linux/lnxEnvironmentResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/linux/lnxFileLineResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/linux/lnxFileResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/linux/lnxGroupResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/linux/lnxPackageResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/linux/lnxScriptResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/linux/lnxServiceResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/linux/lnxSshAuthorizedKeysResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/linux/lnxUserResource.md, dsc/docs-conceptual/dsc-1.1/resources/authoringResourceClass.md, dsc/docs-conceptual/dsc-1.1/resources/authoringResourceComposite.md, dsc/docs-conceptual/dsc-2.0/how-tos/resources/authoring/class-based.md, dsc/docs-conceptual/dsc-2.0/how-tos/resources/authoring/composite.md, dsc/dsc-1.1/PSDesiredStateConfiguration/About/about_Classes_and_DSC.md, dsc/dsc-2.0/PSDesiredStateConfiguration/About/about_Classes_and_DSC.md
=> 3/11/2024 PM Publish

dsc/docs-conceptual/dsc-1.1/pull-server/secureServer.md
=> 4/17/2024 PM Publish

CODE_OF_CONDUCT.md, README.md, dsc/dsc-1.1/PSDesiredStateConfiguration/Invoke-DscResource.md, dsc/dsc-2.0/PSDesiredStateConfiguration/Invoke-DscResource.md, dsc/dsc-3.0/PSDesiredStateConfiguration/Invoke-DscResource.md
=> 5/15/2024 PM Publish

dsc/docs-conceptual/dsc-3.0/changelog.md, dsc/docs-conceptual/dsc-3.0/reference/cli/config/get.md, dsc/docs-conceptual/dsc-3.0/reference/cli/config/set.md, dsc/docs-conceptual/dsc-3.0/reference/cli/config/test.md, dsc/docs-conceptual/dsc-3.0/reference/cli/dsc.md, dsc/docs-conceptual/dsc-3.0/reference/cli/resource/list.md, dsc/docs-conceptual/dsc-3.0/reference/cli/resource/schema.md, dsc/docs-conceptual/dsc-3.0/reference/cli/schema/command.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/config/functions/int.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/config/parameter.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/definitions/resourceKind.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/outputs/config/get.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/outputs/config/set.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/outputs/config/test.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/outputs/resource/list.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/manifest/resolve.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/manifest/root.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/manifest/whatif.md
This change updates the reference documentation and the changelog for the `preview.8` release of DSC v3.
=> 6/24/2024 PM Publish

dsc/docs-conceptual/dsc-1.1/resources/authoringResourceClass.md, dsc/docs-conceptual/dsc-1.1/toc.yml, dsc/docs-conceptual/dsc-2.0/concepts/class-based-resources.md, dsc/docs-conceptual/dsc-2.0/concepts/configurations.md, dsc/docs-conceptual/dsc-2.0/concepts/import-dscresource.md, dsc/docs-conceptual/dsc-2.0/how-tos/configurations/depends-on.md, dsc/docs-conceptual/dsc-2.0/how-tos/configurations/write-and-compile.md, dsc/docs-conceptual/dsc-2.0/how-tos/resources/authoring/class-based.md, dsc/docs-conceptual/dsc-2.0/how-tos/resources/authoring/composite.md, dsc/docs-conceptual/dsc-2.0/overview.md, dsc/docs-conceptual/dsc-2.0/reference/PSDscResources/overview.md, dsc/docs-conceptual/dsc-2.0/toc.yml, dsc/docs-conceptual/dsc-2.0/tutorials/create-class-based-resource.md, dsc/docs-conceptual/dsc-2.0/tutorials/create-dsc-resource-machine-config.md, dsc/docs-conceptual/dsc-3.0/getting-started/getting-started.old.md
- Fixes [AB#327541](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/327541)
- Resolves #267
=> (AB-327541) Update machine configuration terminology

dsc/docs-conceptual/dsc-3.0/concepts/output-accessibility.md, dsc/docs-conceptual/dsc-3.0/toc.yml
* ([AB#330346](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/330346)) Add doc for output accessibility
* Apply suggestions from code review
---------
=> 10/29/2024 PM Publish

dsc/docs-conceptual/dsc-3.0/overview.md
=> Update v3 partner list

dsc/docfx.json
Update ms.topic metadata
- Fixes [AB#368914](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/368914)
=> Update ms.topic metadata

.github/ISSUE_TEMPLATE/04-customer-feedback.yml
=> 3/3/2025 PM Publish

dsc/docs-conceptual/dsc-2.0/reference/PSDscResources/Resources/User/User.md
Fix typo for Description field
=> Fix typo in User.md

dsc/docs-conceptual/dsc-2.0/reference/PSDscResources/Resources/User/User.md
=> 3/12/2025 PM Publish

dsc/docs-conceptual/dsc-3.0/toc.yml
Update TOC for branding
- Fixes [AB#40800](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/40800)
=> Update TOC for branding

dsc/docs-conceptual/dsc-2.0/reference/PSDscResources/Resources/User/User.md
=> 3/18/2025 PM Publish

dsc/docs-conceptual/dsc-3.0/toc.yml
Updates casing for the CLI container in the TOC.
=> (MAINT) Update TOC casing

dsc/docs-conceptual/dsc-3.0/reference/resources/Microsoft/Windows/Registry/index.md
Fix missing closing tag for id anchor.
=> Fix ID anchor in Registry reference documentation

dsc/docs-conceptual/dsc-3.0/reference/cli/resource/test.md
=> (GH-294) Fix syntax for `dsc resource test` reference

dsc/docfx.json
Updates author and the renamed get-started folder (v3 only).
=> (MAINT) Update DocFX config

ThirdPartyNotices.md
See https://ceapex.visualstudio.com/Engineering/_workitems/edit/997743.
=> 4/21/2025 PM Publish

dsc/docs-conceptual/dsc-3.0/toc.yml
Prior to this change, the overview and the article explaining the schema URIs for DSC were missing from the TOC. This change adds entries for those articles.
=> (MAINT) Update TOC for schema articles

dsc/docs-conceptual/dsc-1.1/pull-server/pullClientConfigNames.md, dsc/docs-conceptual/dsc-1.1/pull-server/pullServer.md
Fix broken links
- Fixes [AB#429778](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/429778)
=> Fix broken links

dsc/dsc-2.0/PSDesiredStateConfiguration/Get-DscResource.md, dsc/dsc-2.0/PSDesiredStateConfiguration/New-DscCheckSum.md, dsc/dsc-2.0/PSDesiredStateConfiguration/PSDesiredStateConfiguration.md, dsc/dsc-3.0/PSDesiredStateConfiguration/Get-DscResource.md, dsc/dsc-3.0/PSDesiredStateConfiguration/New-DscChecksum.md, dsc/dsc-3.0/PSDesiredStateConfiguration/PSDesiredStateConfiguration.md
Fix capitalization of the file name and minor edits
- Fixes [AB#433885](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/433885)
=> Fix capitalization of the file name and minor edits

dsc/docs-conceptual/dsc-3.0/overview.md
Prior to this change, it was only implicit that the documentation
directed users to search for an install DSC from the Microsoft
Store with WinGet.
This change makes the directive more explicit and updates the search
command to specify the store as the source to search.
- Fixes #338
=> (GH-338) Clarify WinGet installation in overview

dsc/docs-conceptual/dsc-3.0/changelog.md
This change syncs the changelog for the v3.1.0 release.
The documentation updates will follow in a future change.
=> (Release) Update changelog for v3.1.0

dsc/docs-conceptual/dsc-3.0/changelog.md
=> Add missing details tag

dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/properties/purge.md
Fixes `_purge` example snippet.
=> Fix _purge example
