MicrosoftDocs/PowerShell-Docs-DSC

.openpublishing.publish.config.json
Fixes AB#1916936 - Remove base path from xref_query_tags
=> Remove base path from xref_query_tags

dsc/docs-conceptual/dsc-1.1/pull-server/partialConfigs.md
Since the ```Update-DscConfiguration``` let is *Checks the pull server for an updated configuration and applies it*, there is no need to repeat with the ```Start-DSCConfiguration –UseExisting``` cmdlet to apply the configuration.
Ref:https://docs.microsoft.com/en-us/powershell/module/PSDesiredStateConfiguration/Update-DscConfiguration?view=dsc-1.1
=> Remove unnecessary command from Partial Configurations concept

dsc/docs-conceptual/dsc-1.1/configurations/configurations.md, dsc/docs-conceptual/dsc-3.0/concepts/configurations.md
I was testing this on a Win11 machine, got confused by the resulting error "The term 'WindowsFeature' is not recognized as a name of a cmdlet, function, script file, or executable program." This was due to WindowsFeature not being a client-side component.
Check the boxes below to indicate the content affected by this PR.
**Repository or docset configuration**
**Conceptual documentation**
**Cmdlet reference & about_ topics**
When changing **cmdlet reference** or **about_ topics**, the changes should be copied to all
relevant versions. Check the boxes below to indicate the versions affected by this change.
please add the prefix `WIP:` or `[WIP]` to the beginning of the title and remove the prefix when
the PR is ready.
[contrib]: https://docs.microsoft.com/powershell/scripting/community/contr …
=> Add note on OS-compatibility for the WindowsFeature DSC Resource in examples

.github/workflows/stale-content.yml
This change adds monthly reporting to the repository to inspect the conceptual documentation for stale content (defined as anything with an `ms.date` value more than 330 days older than the current date), writing the report in the console logs, to the GitHub Action summary, and uploading the data in CSV format as a GitHub Action artifact.
=> (AB#4072) Add stale content reporting

dsc/docs-conceptual/dsc-2.0/concepts/configurations.md, dsc/docs-conceptual/dsc-2.0/concepts/get-test-set.md, dsc/docs-conceptual/dsc-2.0/concepts/import-dscresource.md, dsc/docs-conceptual/dsc-2.0/getting-started/invoking-dsc-resources.md, dsc/docs-conceptual/dsc-2.0/how-tos/configurations/depends-on.md, dsc/docs-conceptual/dsc-2.0/how-tos/configurations/write-and-compile.md, dsc/docs-conceptual/dsc-2.0/how-tos/installing-dsc-resources.md, dsc/docs-conceptual/dsc-2.0/how-tos/resources/authoring/checklist.md, dsc/docs-conceptual/dsc-2.0/how-tos/resources/authoring/single-instance.md, dsc/docs-conceptual/dsc-2.0/reference/PSDscResources/Resources/WindowsFeature/Example.md, dsc/docs-conceptual/dsc-2.0/reference/PSDscResources/Resources/WindowsFeatureSet/Install.md, dsc/docs-conceptual/dsc-2.0/reference/PSDscResources/Resources/WindowsFeatureSet/Uninstall.md, dsc/docs-conceptual/dsc-2.0/reference/PSDscResources/Resources/WindowsOptionalFeature/Enable.md, dsc/docs-conceptual/dsc-2.0/reference/PSDscResources/Resources/WindowsOptionalFeatureSet/Disable.md, dsc/docs-conceptual/dsc-2.0/reference/PSDscResources/Resources/WindowsOptionalFeatureSet/Enable.md, dsc/docs-conceptual/dsc-2.0/reference/PSDscResources/Resources/WindowsPackageCab/Install.md, dsc/docs-conceptual/dsc-2.0/reference/PSDscResources/overview.md
There is a known limitation in machine configuration which prevents users from using DSC Resources which call any cmdlets which are not included in PowerShell itself or available from a module on the Gallery. This includes the built-in Windows modules, like **DISM**.
This change updates the documentation to:
- Alert readers to this limitation where sensible
- Replace examples in the conceptual docs which point to DSC Resources that won't work in machine configuration with ones that will
- Ensure all conceptual docs which apply only to machine configuration say so at the top of the document.
This change fixes [AB#5227](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5227).
[contrib]: https://docs.microsoft.com/powershell/scripting/community/contribut …
=> (AB#5227) Address machine config limits for DSC Resources

dsc/docfx.json
Prior to this change, the DocFX configuration for this repository used the generic feedback hub for all product feedback on DSC (separate from the docs feedback).
This change:
- Sets the default product feedback URL to the issue picker for the now open-sourced **PSDesiredStateConfiguration** module on GitHub
- Adds an override for the v1.1 docs to continue to point at the generic feedback hub instructions
- Fixes [AB#5130](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5130)
=> (AB#5130) Update feedback URLs in DocFX

dsc/docs-conceptual/dsc-1.1/resources/resources.md
The resource names in example are not valid. A required resource name should be in the format `[<typename>]<name>`, with alphanumeric characters, spaces, `_`, `-`, `.` and `\`.
=> Fix incorrect resource name in example

dsc/docs-conceptual/dsc-2.0/concepts/class-based-resources.md
Prior to this change, the documentation did not mention the differences between reference and value types as they apply to DSC Resources.
This change adds the _Default property values_ section, which explains the intialization of a DSC Resource's properties. Particularly, it covers their default values and how that differs between reference types and value types.
It clarifies the impact of this, namely that a DSC Resource can't know with certainty whether a value-type properties was specified as its default value or not specified at all and therefore can't be written to treat those properties as unmanaged if their default value is a valid value for that property.
It also updates the _Use enums instead of ValidateSet_ section to call out the impact this has on enums and advises readers …
=> (MAINT) Document reference and value types for class-based DSC Resources

dsc/docfx.json
Fixes [AB#28009](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/28009) - Add src path for index.md
This change should ensure that index.md gets built in the proper location so that we have a file to redirect from.
=> Change src path for index.md

.vscode/cspell/dsc/cspell.yaml, .vscode/cspell/dsc/dictionaries/dsc-terms.txt, dsc/docs-conceptual/dsc-1.1/resources/authoringResourceClass.md, dsc/docs-conceptual/dsc-1.1/toc.yml, dsc/docs-conceptual/dsc-2.0/concepts/class-based-resources.md, dsc/docs-conceptual/dsc-2.0/concepts/configurations.md, dsc/docs-conceptual/dsc-2.0/concepts/import-dscresource.md, dsc/docs-conceptual/dsc-2.0/how-tos/configurations/depends-on.md, dsc/docs-conceptual/dsc-2.0/how-tos/configurations/write-and-compile.md, dsc/docs-conceptual/dsc-2.0/how-tos/resources/authoring/class-based.md, dsc/docs-conceptual/dsc-2.0/how-tos/resources/authoring/composite.md, dsc/docs-conceptual/dsc-2.0/overview.md, dsc/docs-conceptual/dsc-2.0/reference/PSDscResources/overview.md, dsc/docs-conceptual/dsc-2.0/toc.yml, dsc/docs-conceptual/dsc-2.0/tutorials/create-class-based-resource.md, dsc/docs-conceptual/dsc-3.0/concepts/resources.md, dsc/docs-conceptual/dsc-3.0/getting-started/getting-started.md
This change updates the documentation across the versions for the **Reasons** property required by Azure Automanage's machine configuration feature.
Prior to this change, the documentation showed creating a class for the **Reasons** complex property called `Reason`. While this works, it also leads DSC Resource authors towards implementing the class with that name, which leads to errors when compiling a configuration that uses two or more modules that define a class with the same name.
This change:
- Updates the how-to documentation for authoring a class-based DSC Resource across every version to use a prefix before the class name for the complex property and note why the prefix is used
- Add a new section to the conceptual documentation for class-based DSC Resources in v2 to explain the …
=> (GH-126) Update docs for Reasons property

dsc/docs-conceptual/dsc-2.0/toc.yml, dsc/docs-conceptual/dsc-2.0/tutorials/create-dsc-resource-machine-config.md
Prior to this change, the only tutorial for writing a class-based DSC Resource was for resources not intended for use with the machine configuration feature of Azure Automanage.
This change adds a specific authoring tutorial for that use case, including the usage of the **Reasons** property for reporting how the DSC Resource is out of the desired state.
- Fixes [AB#5183](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5183)
=> (AB#5183) Add tutorial for machine config

dsc/docs-conceptual/dsc-3.0/getting-started/getting-started.md
Prior to this change, the example code for the v3 getting started article showed passing the parameters for `Invoke-DscResource` as a hash directly to the command.
This change fixes the examples by storing the parameter values as a hashtable in a variable and then splatting the hash table with the cmdlet execution.
- Fixes [AB#82869](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/82869)
- Resolves #147
=> (GH-147) Fix v3 getting started examples

dsc/docs-conceptual/dsc-2.0/overview.md
Prior to this change, it wasn't obvious to end-users that the built-in DSC Resources from v1.1 aren't available in DSC v2 and later.
This change:
- Adds information about the removed DSC Resources to the v2 overview, including linking to the replacement DSC Resources in **PSDscResources**.
- Fixes [AB#91783](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/91783)
=> (AB#91783) Clarify removal of builtin DSC Resources

dsc/docs-conceptual/dsc-2.0/overview.md
Prior to this change, it wasn't obvious to end-users that the built-in DSC Resources from v1.1 aren't available in DSC v2 and later.
This change:
- Adds information about the removed DSC Resources to the v2 overview, including linking to the replacement DSC Resources in **PSDscResources**.
- Fixes [AB#91783](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/91783)
=> 5/23 PM Publish

dsc/docs-conceptual/dsc-3.0/reference/microsoft/osinfo/cli/osinfo.md, dsc/docs-conceptual/dsc-3.0/reference/microsoft/osinfo/examples/osinfo.config.dsc.yaml, dsc/docs-conceptual/dsc-3.0/reference/microsoft/osinfo/examples/validate-in-a-configuration.md, dsc/docs-conceptual/dsc-3.0/reference/microsoft/osinfo/examples/validate-with-dsc-resource.md, dsc/docs-conceptual/dsc-3.0/reference/microsoft/osinfo/overview.md, dsc/docs-conceptual/dsc-3.0/reference/microsoft/osinfo/resource.md, dsc/docs-conceptual/dsc-3.0/reference/microsoft/windows/registry/cli/config/command.md, dsc/docs-conceptual/dsc-3.0/reference/microsoft/windows/registry/cli/config/get.md, dsc/docs-conceptual/dsc-3.0/reference/microsoft/windows/registry/cli/config/set.md, dsc/docs-conceptual/dsc-3.0/reference/microsoft/windows/registry/cli/config/test.md, dsc/docs-conceptual/dsc-3.0/reference/microsoft/windows/registry/cli/find/command.md, dsc/docs-conceptual/dsc-3.0/reference/microsoft/windows/registry/cli/query/command.md, dsc/docs-conceptual/dsc-3.0/reference/microsoft/windows/registry/cli/registry.md, dsc/docs-conceptual/dsc-3.0/reference/microsoft/windows/registry/cli/remove/command.md, dsc/docs-conceptual/dsc-3.0/reference/microsoft/windows/registry/cli/schema/command.md, dsc/docs-conceptual/dsc-3.0/reference/microsoft/windows/registry/cli/set/command.md, dsc/docs-conceptual/dsc-3.0/reference/microsoft/windows/registry/cli/test/command.md, dsc/docs-conceptual/dsc-3.0/reference/microsoft/windows/registry/examples/Add-RegistryKey.ps1, dsc/docs-conceptual/dsc-3.0/reference/microsoft/windows/registry/examples/Remove-RegistryKey.ps1, dsc/docs-conceptual/dsc-3.0/reference/microsoft/windows/registry/examples/Remove-RegistryValue.ps1, dsc/docs-conceptual/dsc-3.0/reference/microsoft/windows/registry/examples/Set-RegistryValue.ps1, dsc/docs-conceptual/dsc-3.0/reference/microsoft/windows/registry/examples/Update-RegistryValue.ps1, dsc/docs-conceptual/dsc-3.0/reference/microsoft/windows/registry/examples/configure-registry-keys-and-values.md, dsc/docs-conceptual/dsc-3.0/reference/microsoft/windows/registry/examples/manage-a-registry-key.md, dsc/docs-conceptual/dsc-3.0/reference/microsoft/windows/registry/examples/manage-a-registry-value.md, dsc/docs-conceptual/dsc-3.0/reference/microsoft/windows/registry/examples/registry.config.dsc.yaml, dsc/docs-conceptual/dsc-3.0/reference/microsoft/windows/registry/overview.md, dsc/docs-conceptual/dsc-3.0/reference/microsoft/windows/registry/resource.md, dsc/docs-conceptual/dsc-3.0/toc.yml
This change adds reference documentation for the proof-of-concept prototype command-based DSC Resources `Microsoft/OSInfo` and `Microsoft.Windows/Registry`.
The reference documentation proposes a structure for the reference documentation for command-based resources based on the reference documentation used for the PSDscResources in v2.
It also documents the command-line tools the resources use.
While these commands and resources are not production-ready, they are the only command-based resources we can reference in the documentation at this time. If the resources are removed or replaced in the future, the documentation can be updated.
This change:
- Fixes [AB#118304](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/118304)
- Fixes …
=> (AB#118304) Add reference docs for command-based resources

dsc/docs-conceptual/dsc-3.0/reference/cli/dsc.md, dsc/docs-conceptual/dsc-3.0/reference/cli/schema/command.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/config/document.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/config/parameter.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/config/resource.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/definitions/message.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/definitions/parameters/dataTypes.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/definitions/resourceType.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/outputs/config/get.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/outputs/config/set.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/outputs/config/test.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/outputs/resource/get.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/outputs/resource/list.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/outputs/resource/set.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/outputs/resource/test.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/manifest/get.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/manifest/provider.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/manifest/root.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/manifest/schema/embedded.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/manifest/schema/property.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/manifest/set.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/manifest/test.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/manifest/validate.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/properties/ensure.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/properties/inDesiredState.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/properties/purge.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/properties/rebootRequested.md
Prior to this change, the metadata YAML blocks for schemas and CLI parameters included spaces in the keyword names, aligned colons, and used block syntax.
The platform does not render keywords correctly when they include spaces or when there is space between the keyword and the colon.
This change standardizes the formatting so that keywords are correctly highlighted. It also switches to using flow syntax for arrays, keeping them on one line if the array fits or breaking across indented lines otherwise.
=> (MAINT) Fix rendering for YAML metadata

dsc/docs-conceptual/dsc-1.1/troubleshooting/troubleshooting.md
Prior to this change, the troubleshooting documentation for DSC v1.1 only listed the `dsccore` provider for retrieving the DSC process ID, not the `dsctimer` provider.
This change:
- Updates the code example to include a filter for both providers.
- Cleans up grammar, style, and formatting.
- Resolves #192
=> (GH-192) Update troubleshooting for v1.1

dsc/docs-conceptual/dsc-1.1/troubleshooting/troubleshooting.md
Prior to this change, the troubleshooting documentation for DSC v1.1 only listed the `dsccore` provider for retrieving the DSC process ID, not the `dsctimer` provider.
This change:
- Updates the code example to include a filter for both providers.
- Cleans up grammar, style, and formatting.
- Resolves #192
=> 8/30/2023 PM Publish

dsc/docs-conceptual/dsc-1.1/reference/resources/windows/registryResource.md
Fixed typo - `REG-BINARY` changed to `REG_BINARY`. The underscore is documented at [Registry Value Types - Microsoft Learn](https://learn.microsoft.com/en-us/windows/win32/sysinfo/registry-value-types)
=> Fixed typo - `REG-BINARY` changed to `REG_BINARY`

dsc/docs-conceptual/dsc-1.1/reference/resources/windows/scriptResource.md, dsc/docs-conceptual/dsc-2.0/reference/PSDscResources/Resources/Script/Script.md
Prior to this change, the documentation for the built-in `Script` resource made no mention of the drawbacks to using the resource and didn't direct readers to consider implementing their own resource instead.
This change:
- Updates the note for the `Script` resource in the **PSDscResources** module to explicitly suggest readers implement a custom resource.
- Adds the same note with the information about the drawbacks of the `Script` resource to the v1.1 built-in resource documentation.
- Resolves #224
- Fixes [AB#187561](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/187561)
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/pow …
=> (GH-224) Discourage use of `Script` resource

dsc/docs-conceptual/dsc-1.1/reference/resources/windows/scriptResource.md, dsc/docs-conceptual/dsc-2.0/reference/PSDscResources/Resources/Script/Script.md
Prior to this change, the documentation for the built-in `Script` resource made no mention of the drawbacks to using the resource and didn't direct readers to consider implementing their own resource instead.
This change:
- Updates the note for the `Script` resource in the **PSDscResources** module to explicitly suggest readers implement a custom resource.
- Adds the same note with the information about the drawbacks of the `Script` resource to the v1.1 built-in resource documentation.
- Resolves #224
- Fixes [AB#187561](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/187561)
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/pow …
=> 12/1/2023 PM Publish

dsc/docs-conceptual/dsc-1.1/reference/resources/packagemanagement/PackageManagementDscResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/packagemanagement/PackageManagementSourceDscResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/windows/fileResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/windows/packageResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/windows/registryResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/windows/serviceResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/windows/serviceSetResource.md, dsc/docs-conceptual/dsc-1.1/reference/resources/windows/windowsFeatureSetResource.md
Add missing `Import-DSCResource` statements to all configuration blocks in examples.
- Resolves #233
- Fixes [AB#196403](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/196403)
=> (GH-233) Add `Import-DSCResource`

dsc/dsc-1.1/PSDesiredStateConfiguration/Invoke-DscResource.md, dsc/dsc-2.0/PSDesiredStateConfiguration/Invoke-DscResource.md, dsc/dsc-3.0/PSDesiredStateConfiguration/Invoke-DscResource.md
Prior to this change, the reference documentation for `Invoke-DscResource` didn't clearly state that the cmdlet is incompatible with composite resources.
This change:
- Clarifies that `Invoke-DscResource` can't be used to invoke composite resources, which require the LCM.
- Resolves #258
- Fixes [AB#255214](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/255214)
=> (GH-258) Clarify `Invoke-DscResource` is incompatible with composite resources

dsc/docs-conceptual/dsc-3.0/concepts/output-accessibility.md, dsc/docs-conceptual/dsc-3.0/toc.yml
Adds an edited draft of the output accessibility document for DSC v3.
=> (AB#330346) Add doc for output accessibility

dsc/docs-conceptual/dsc-3.0/concepts/output-accessibility.md, dsc/docs-conceptual/dsc-3.0/toc.yml
Publishing latest changes to live
=> Publish to live

dsc/docfx.json, dsc/docs-conceptual/dsc-3.0/overview.md
=> 02/04/2025 PM Publishing

dsc/docs-conceptual/dsc-3.0/reference/cli/resource/test.md, dsc/docs-conceptual/dsc-3.0/reference/resources/Microsoft/Windows/Registry/index.md
=> 3/27/2025 PM Publish

dsc/docs-conceptual/dsc-3.0/get-started/index.md
This change removes an erroneous dash from an example command, and fixes #307
=> 4/7/2025 PM Publish

dsc/docs-conceptual/dsc-3.0/concepts/output-accessibility.md
=> 4/15/2025 PM Publish

dsc/docs-conceptual/dsc-1.1/pull-server/pullClientConfigNames.md, dsc/docs-conceptual/dsc-1.1/pull-server/pullServer.md
=> 5/8/2025 PM Publish

dsc/docs-conceptual/dsc-3.0/concepts/resources/operations.md
In the Get operation section, it erroneously mentions that DSC invokes the "Test" operation. It has been changed to be the "Get" operation.
=> Fix Get operation text

dsc/docs-conceptual/dsc-3.0/concepts/resources/operations.md
=> 5/12/2025 PM Publish

dsc/dsc-2.0/PSDesiredStateConfiguration/Get-DscResource.md, dsc/dsc-2.0/PSDesiredStateConfiguration/New-DscCheckSum.md, dsc/dsc-2.0/PSDesiredStateConfiguration/PSDesiredStateConfiguration.md, dsc/dsc-3.0/PSDesiredStateConfiguration/Get-DscResource.md, dsc/dsc-3.0/PSDesiredStateConfiguration/New-DscChecksum.md, dsc/dsc-3.0/PSDesiredStateConfiguration/PSDesiredStateConfiguration.md
=> 5/19/2025 PM Publish

dsc/docs-conceptual/dsc-3.0/overview.md
Prior to this change, it was only implicit that the documentation directed users to search for an install DSC from the Microsoft Store with WinGet.
This change makes the directive more explicit and updates the search command to specify the store as the source to search.
=> 6/9/2025 PM Publish

dsc/docs-conceptual/dsc-3.0/changelog.md, dsc/dsc-1.1/PSDesiredStateConfiguration/New-DscChecksum.md, dsc/dsc-2.0/PSDesiredStateConfiguration/New-DscChecksum.md, dsc/dsc-3.0/PSDesiredStateConfiguration/New-DscChecksum.md
=> 6/19/2025 PM Publish

dsc/docs-conceptual/dsc-3.0/reference/schemas/definitions/resourceKind.md, dsc/docs-conceptual/dsc-3.0/reference/schemas/resource/manifest/root.md
Prior to this change, the resource `kind` in the root manifest reference wasn't updated to reflect the correct casing or all valid options. This change:
- Ensures that the reference in the manifest root matches the subschema reference.
- Fixes #359
=> (GH-359) Fix resource `kind`
